title: Playform Documentation
description: Image Generator and AI Art using Playform.
url: https://artrendex.github.io
baseurl: /Playform-docs
theme: minima
plugins:
  - jekyll-seo-tag

minima:
  nav_pages:
    - image-generation-suite.md
    - facecraft-suite.md
    - prompt-free-generation.md
    - faq.md



# header_pages::
#     - image-generation-suite.md
#     - face-craft-suite.md
#     - faq.md

# nav:
#   - title: "Home"
#     url: "/"
#   - title: "Image Generation Suite"
#     url: "./image-generation-suite.md"
#   - title: "FaceCraft Suite"
#     url: "./facecraft-suite.md"
#   - title: "Prompt Free Generation"
#     url: "./prompt-free-generation.md"
#   - title: "FAQ"
#     url: "./faq.md"